sudo: false
language: python
cache: pip
matrix:
  include:
  - python: 3.7
    dist: xenial
    env: TF=2
  - python: 3.6
    dist: xenial
    env: TF=2
  - python: 3.5
    dist: xenial
    env: TF=1
env:
  global:
  - COVERALLS_PARALLEL=true
  - LOGGING=info
install:
- pip install -r requirements.txt
- pip install wheel pytest pytest-cov absl-py --upgrade
- if [ "$TF" = "2" ]; then pip install tensorflow==2.0; fi
- if [ "$TF" = "1" ]; then pip install tensorflow==1.13.2; fi
- pip install torch==1.3.0+cpu torchvision==0.4.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
- python3 setup.py bdist_wheel
- pip install dist/PennyLane*.whl
script:
- make coverage
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: de0sN7zGO8bRzsNf94L0KQrAARpyYHqkzyWAvfOO8uWwGbai2JE5gd62Qo0twpvx7SrXQiSmVWs8A2rKV8PBNTSMFH9csWENzaDN34oveu/faVB3R3zmlxuV5G3sAh5nUfNuy+H4cPuIa4zgDtHm8V7R/rkzxgj/R0QAGsfRJKvLzkoEjOYimuYGjgFFyi3md0S0AKUaNU90+KVgVJFt09+r443HmI6fdvT9b3MZJVREeCDcKUuiIrgeWtpIcfprNMBSrJQ4zr+xW1b2QtxTokXF/GXBrFL/uUp6UYTfxgit1mY9tDgoASddUEI3P0cCy51MebvxScfbZyWfuFufbTwHV+ExnEqJ0zZu6Oo3J5cZjfFGNMA9TTcAFtXC8+IQN5DGFbcczs34pKuacVAS+/+bnv8q5vJy7Wg0luokyZ4Y4na6KDoC2g12oC6hk0qt/gYV75H/Jslol56bAOhcsqwKbY/o9xxkzZMwhIXn8h0xCtIU8g8WJdIX3xkYVQhKr6RqqLaQ6Eqj/IccJIEALTZ7Q7KT9D/dZpCKR3uNap0jSyi9IzTn/wSu8ebjOa7xzV1DvNhx8TIRqynSb5n9aObIyGOQqdYCwUp+elEakLJJNYdfBl17sSIp7tiUSGqYDRhsP3vu8wbOasSXW9Qk7PukUWoSLgsVXS0C88lGYzw=

jobs:
  include:
    - stage: qchem
      install:
      # apt dependencies
      - sudo apt install openbabel
      # install conda
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - source "$HOME/miniconda/etc/profile.d/conda.sh"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      # Useful for debugging any issues with conda
      - conda info -a
      # create a virtual env
      - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      - conda activate test-environment
      # install PennyLane and Qchem
      - pip install -r requirements.txt
      - pip install wheel pytest pytest-cov --upgrade
      - python3 setup.py bdist_wheel
      - pip install dist/PennyLane*.whl
      - cd qchem && python3 setup.py bdist_wheel && cd ../
      - pip install qchem/dist/PennyLane_Qchem*.whl
      script: make -C qchem coverage
      python: 3.7
      dist: xenial
